# Whenever a new tag is pushed, this workflow should run "GOPROXY=proxy.golang.org go list -m github.com/wernerstrydom/go-semver@v1.0.0" where v1.0.0 is the tag that was pushed.

name: Publish
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.20'

        - name: Publish
          run: GOPROXY=proxy.golang.org go list -m github.com/${{ github.repository }}@${{ github.ref_name }}